In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')              

In [3]:
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [5]:
tit_df = titanic_train.head()
tit_df

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  156 non-null    int64  
 1   Survived     156 non-null    int64  
 2   Pclass       156 non-null    int64  
 3   Name         156 non-null    object 
 4   Sex          156 non-null    object 
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64  
 7   Parch        156 non-null    int64  
 8   Ticket       156 non-null    object 
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     object 
 11  Embarked     155 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB


In [7]:
titanic_train.shape

(156, 12)

In [8]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [9]:
tit_df.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [10]:
a = tit_df.dtypes[tit_df.dtypes == 'object'].index
a

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [11]:
tit_df[a].describe()

Name     Sex     Ticket Cabin Embarked
count                        5       5          5     2        5
unique                       5       2          5     2        2
top     Heikkinen, Miss. Laina  female  A/5 21171  C123        S
freq                         1       3          1     1        4

In [13]:
tit_df.describe()

PassengerId  Survived    Pclass       Age     SibSp  Parch       Fare
count     5.000000  5.000000  5.000000   5.00000  5.000000    5.0   5.000000
mean      3.000000  0.600000  2.200000  31.20000  0.600000    0.0  29.521660
std       1.581139  0.547723  1.095445   6.83374  0.547723    0.0  30.510029
min       1.000000  0.000000  1.000000  22.00000  0.000000    0.0   7.250000
25%       2.000000  0.000000  1.000000  26.00000  0.000000    0.0   7.925000
50%       3.000000  1.000000  3.000000  35.00000  1.000000    0.0   8.050000
75%       4.000000  1.000000  3.000000  35.00000  1.000000    0.0  53.100000
max       5.000000  1.000000  3.000000  38.00000  1.000000    0.0  71.283300

In [14]:
tit_df[['Name','Sex','Age']]

Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [20]:
# we are slicing the dataframe from 5th row to 9th row with the jump size of 2
sorted(tit_df["Name"])[0:4:2]

['Allen, Mr. William Henry',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)']

In [17]:
tit_df

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [21]:
tit_df['Name'].describe()

count                          5
unique                         5
top       Heikkinen, Miss. Laina
freq                           1
Name: Name, dtype: object

In [27]:
tit_df[["Ticket"]][0:5]

Ticket
0         A/5 21171
1          PC 17599
2  STON/O2. 3101282
3            113803
4            373450

In [33]:
# second method
tit_df.loc[0:4,["Ticket"]]

Ticket
0         A/5 21171
1          PC 17599
2  STON/O2. 3101282
3            113803
4            373450

In [35]:
# third method
tit_df[0:5][['Ticket']]


Ticket
0         A/5 21171
1          PC 17599
2  STON/O2. 3101282
3            113803
4            373450

In [36]:
tit_df['Ticket'].describe()

count             5
unique            5
top       A/5 21171
freq              1
Name: Ticket, dtype: object

In [37]:
tit_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [38]:
tit_df.index

RangeIndex(start=0, stop=5, step=1)

In [41]:
# 1st method
tit_df["Cabin"][0:3]

0    NaN
1    C85
2    NaN
Name: Cabin, dtype: object

In [43]:
tit_df.loc[:4,['Cabin']]

Cabin
0   NaN
1   C85
2   NaN
3  C123
4   NaN

In [44]:
tit_df["Name"].uniqueque()

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry'], dtype=object)

In [45]:
tit_df

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [46]:
tit_df['Survived'] ==1

0    False
1     True
2     True
3     True
4    False
Name: Survived, dtype: bool

In [47]:
tit_df[tit_df['Survived'] ==1].shape

(3, 12)

In [49]:
# we Can See See the details of Categorial Data
new_Pclass = pd.Categorical(tit_df["Pclass"])
new_Pclass

[3, 1, 3, 1, 3]
Categories (2, int64): [1, 3]

In [50]:
new_Pclass.dtype

CategoricalDtype(categories=[1, 3], ordered=False)

In [52]:
new_Pclass = pd.Categorical(tit_df['Sex'])
new_Pclass

['male', 'female', 'female', 'female', 'male']
Categories (2, object): ['female', 'male']

In [56]:
char_cabin = tit_df["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin

['n', 'C', 'n', 'C', 'n']
Categories (2, object): ['C', 'n']

In [57]:
tit_df['Cabin'] = new_Cabin

<ipython-input-57-f98952e3db6a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tit_df['Cabin'] = new_Cabin


In [58]:
tit_df

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     n        S  
1      0          PC 17599  71.2833     C        C  
2      0  STON/O2. 3101282   7.9250     n        S  
3      0            113803  53.1000     C        S  
4      0            373450   8.0500     n        S

In [60]:
tit_df[['Age']].isnull()

Age
0  False
1  False
2  False
3  False
4  False

In [61]:
tit_df['Age'].isnull()

0    False
1    False
2    False
3    False
4    False
Name: Age, dtype: bool

In [75]:
missing = np.where(tit_df['Cabin'] == 'n')

In [76]:
print(missing)
print()
len(missing[0])

(array([0, 2, 4], dtype=int64),)



3

In [65]:
missing = np.where(tit_df['Cabin'].isnull() == True)
missing

(array([], dtype=int64),)

In [66]:
tit_df.Age.iloc[3]

35.0

In [67]:
np.where(tit_df["Fare"]==max(tit_df["Fare"]))


(array([1], dtype=int64),)

In [68]:
tit_df

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     n        S  
1      0          PC 17599  71.2833     C        C  
2      0  STON/O2. 3101282   7.9250     n        S  
3      0            113803  53.1000     C        S  
4      0            373450   8.0500     n        S

In [69]:
np.where(tit_df['Pclass'] == max(tit_df['Pclass']))

(array([0, 2, 4], dtype=int64),)

In [77]:
tit_df['Family'] =tit_df["SibSp"] + tit_df['Parch']
tit_df['Family']

<ipython-input-77-c6168ecc1801>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tit_df['Family'] =tit_df["SibSp"] + tit_df['Parch']


0    1
1    1
2    0
3    1
4    0
Name: Family, dtype: int64

In [78]:
tit_df

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Family  
0      0         A/5 21171   7.2500     n        S       1  
1      0          PC 17599  71.2833     C        C       1  
2      0  STON/O2. 3101282   7.9250     n        S       0  
3      0            113803  53.1000     C        S       1  
4      0            373450   8.0500     n        S       0

In [80]:
most_family = np.where(tit_df['Family'] == max(tit_df['Family']))
most_family

(array([0, 1, 3], dtype=int64),)

In [84]:
len(most_family[0])

3

In [85]:
tit_df.iloc[most_family]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch     Ticket     Fare Cabin Embarked  Family  
0      0  A/5 21171   7.2500     n        S       1  
1      0   PC 17599  71.2833     C        C       1  
3      0     113803  53.1000     C        S       1

In [86]:
tit_df.loc[missing]

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  Family  
0      1      0         A/5 21171  7.250     n        S       1  
2      0      0  STON/O2. 3101282  7.925     n        S       0  
4      0      0            373450  8.050     n        S       0